theme: jekyll-theme-modernist
# Name of website
title: Softreck

# Short description of your site
description: Leadership Through Software Development

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources:
    - Page: "https://softreck.github.io/logo"
    - logo: "https://softreck.github.io/logo/softreck_transparent_logo_128.png"
  home: "http://softreck.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/softreck_transparent_logo_128.png"
